---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-adminweb
spec:
  type: NodePort
  ports:
  - name: rabbitmq-web
    port: 15672
    targetPort: 15672
    nodePort: 32001
  selector:
    app: rabbitmq-micro
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-server
spec:
 ports:
 - port: 5672
 selector:
   app: rabbitmq-micro
