---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-micro-conf
data:
  redis-micro.conf: |
        bind 0.0.0.0
        port 6379
        pidfile .pid
        appendonly yes
        cluster-config-file nodes-6379.conf
        pidfile /data/redis/log/redis30.pid
        cluster-config-file /data/redis/conf/redis-micro.conf
        dir /data/redis/data/
        logfile "/data/redis/log/redis-micro.log"
        cluster-node-timeout 5000
