---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongo-1
  namespace: default
  labels:
    app: mongo-cluster
spec: 
  selector: 
    matchLabels: 
      name: mongo-1
  serviceName: "mongo-1"
  replicas: 1
  podManagementPolicy: Parallel
  template: 
    metadata: 
      labels: 
        name: mongo-1
        app: mongo-cluster
    spec: 
      terminationGracePeriodSeconds: 10
      # 该部分内容是为了多实例部署时，部署在同一个节点上，所以使用互斥性
      #affinity: 
      #   podAntiAffinity: 
      #     requiredDuringSchedulingIgnoredDuringExecution: 
      #     - labelSelector: 
      #         matchExpressions: 
      #         - key: "name"
      #           operator: In
      #           values: 
      #           - mongo
      #       topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-redis
        image: busybox:1.35
        command: ['sh', '-c', 'mkdir -p /mongo/data; mkdir -p /mongo/log; mkdir -p /mongo/key']
        volumeMounts:
        - name: mongo-data
          mountPath: /mongo/
      containers: 
      - name: mongo
        image: mongo:4.2
        imagePullPolicy: IfNotPresent
        command:  
        - mongod 
        - "-f"
        - "/etc/mongod.conf"
        - "--bind_ip_all"
        ports: 
        - containerPort: 27017
        volumeMounts: 
        - name: mongo-cnf-volume
          mountPath: /etc/mongod.conf/
          subPath: mongod.conf
        - name: mongo-data
          mountPath: /mongo
      volumes:
        - name: mongo-cnf-volume     #映射configMap信息
          configMap:
            name: mongodb-conf
            items:
              - key: mongod.conf
                path: mongod.conf
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
---
