apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mall-monitor
  #namespace: ms 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ms
      app: mall-monitor
  template:
    metadata:
      labels:
        project: ms 
        app: mall-monitor
    spec:
      imagePullSecrets:
      - name: tiger-registry
      containers:
      - name: mall-monitor
        image: 192.168.18.132/micro/mall-monitor:2022-04-22-14-34-03
        imagePullPolicy: Always
        ports:
          - protocol: TCP
            containerPort: 8101
        env:
          - name: JAVA_OPTS
            value: "-Xmx1g"
        resources:
          requests:
            cpu: 0.5
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 8101
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8101
          initialDelaySeconds: 60
          periodSeconds: 10
