apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc1
spec:
  containers:
  - name: nginx-1
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: volume-1
      mountPath: /usr/share/nginx/html
  volumes:
    - name: volume-1
      persistentVolumeClaim:
        claimName: pvc1
        readOnly: false
        
