apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-3
  #namespace: tiger
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi                      #设置容量为5G，`应该是无法匹配到任何pv`
