run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - promlinter
    - revive
    - staticcheck
    - unconvert

linters-settings:
  goimports:
    local-prefixes: k8s.io/kube-state-metrics

issues:
  exclude-use-default: false
  exclude-rules:
    # We don't check metrics naming in the tests.
    - path: _test\.go
      linters:
        - promlinter
