---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage2105"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
