apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config5
  namespace: default
data:
  redis_host: redis-svc.default.cluster.svc.local
  redis_port: "6379"
  redis_prefix: "/usr/local/redis/"
  app-dev.conf: |
    property.1 = value-1
    property.2 = value-2
    property.3 = value-3
    property.4 = value-4
  my.cnf: |
    [mysqld]
    port = 3306
    log-bin = mysql-bin
    haha = hehe
