apiVersion: v1
kind: Pod
metadata:
  name: nginx-config10
  labels:
    app: nginx-configmap
spec:
  containers:
  - name: nginx-configmap2
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume4
      mountPath: "/tmp/config4"
  volumes:
  - name: config-volume4
    configMap:
      name: test-config3
      items:
      - key: my.cnf
        path: mysql-key
      - key: app-dev.config
        path: app-config
