apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod2
spec:
  containers:
    - name: test-container
      image: nginx
      imagePullPolicy: IfNotPresent
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never
