apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      imagePullPolicy: IfNotPresent
      env:
        - name: L_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: T_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type
  restartPolicy: Never
