kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-svc
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31072
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30072
  selector:
    app: rabbitmq-micro-deployment

