apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq-micro-deployment
  name: rabbitmq-micro-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-micro-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: rabbitmq-micro-deployment
    spec:
      containers:
      - image: rabbitmq:3.7.14
        name: rabbitmq
        volumeMounts:
          - name: config-volume
            mountPath: /etc/rabbitmq
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          # See a note on cluster_formation.k8s.address_type in the config file section
          - name: K8S_SERVICE_NAME
            value: rabbitmq-svc
          - name: RABBITMQ_NODENAME
            value: $(K8S_SERVICE_NAME)
          - name: RABBITMQ_ERLANG_COOKIE
            value: "mycookie"
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-micro-conf
            items:
            - key: enabled_plugins
              path: enabled_plugins
            - key: rabbitmq.conf
              path: rabbitmq.conf

